print("Hello")
print("Welcome to my quiz about birds!")
print(" /\ /\\")
print("((ovo))")
print("():::()")
print("  VVV")
q1 = input("1. What is your favorite bird?")
print("Great choice! I like "+q1+"s too!")
q2 = input("2. Why do you like that bird?")
q3 = input("3. What is your bird's favorite food?")
q4= input("4. What do most birds use to fly? ")
q5=input("5.")
