print("Hello")
print("Welcome to my quiz about birds!")
print(" /\ /\\")
print("((ovo))")
print("():::()")
print("  VVV")
q1 = input("1. What is your favorite bird?")
print("Great choice! I like "+q1+"s too!")
q2=input("Do you have yourself bird?")
q3 = input("2. Why do you like that bird?")
q4 = input("3. What is your bird's favorite food?")
q5= input("4. What do most birds use to fly? ")
print("Thanks for taking the quiz! I hope you enjoyed it!")
